server:
  port: 20000

eureka:

  instance:
    hostname: register

  client:

    registerWithEureka: false

    fetchRegistry: false

    serviceUrl:
      defaultZone: http://127.0.0.1:20000/eureka/
