#-----------------------------------------------------FEIGN-------------------------------------------------------
feign:
  hystrix:
    enabled: true
#  httpclient:
#    enabled: true
#-----------------------------------------------------bus sleuth--------------------------------------------------

server:
  port: 29999

# 服务注册   服务发现配置
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:20000/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html

#spring:
#  application:
#    name: demo-service
#  cloud:
#    config:
#      discovery:
#        enabled: true #开启配置中心服务
#        service-id: config-service #配置中心服务名
#      profile: dev
#test:
#  val: sultan-dev

spring:
  profiles:
    active: dev
  application:
    name: direct-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    zookeeper:
      enabled: false
    bus:
      trace:
        enabled: true
  sleuth:
    web:
      client:
        enabled: true
  redis:
    database: 1
    # Redis服务器地址
    host: 192.168.92.129
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password: 123456
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 100
      # 连接池中的最小空闲连接
      min-idle: 1
    # 连接超时时间（毫秒）
    timeout: 30000
    jedis:
      pool:
        max-idle: 1000

  #-------------------------------------------------- DATASOURCE---------------------------------------------------
  datasource:
    #      url: jdbc:mysql://${spring.datasource.ip}:${spring.datasource.port}/${spring.datasource.database}?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&autoReconnect=true
    url: jdbc:mysql://${spring.datasource.ip}:${spring.datasource.port}/${spring.datasource.database}?useUnicode=true&characterEncoding=utf-8
    ip: 192.168.50.51
    port: 3306
    database: mydb
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: 'stat,wall,slf4j'
    poolPreparedStatements: false
    initialSize: 5
    minIdle: 5
    maxActive: 100
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: 'select ''x'''
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    maxOpenPreparedStatements: 20
    connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000

#-----------------------------------------------------RIBBON------------------------------------------------------
ribbon:
  ServerListRefreshInterval: 1000
  ConnectTimeout: 10000
  ReadTimeout: 30000
  #默认只对get请求重试，设置true时，post请求也会重试。
  OkToRetryOnAllOperations: false
  #是每台服务器最多重试次数，，但是首次调用不包括在内
  MaxAutoRetries: 1
  #是最多重试多少台服务器。
  MaxAutoRetriesNextServer: 2
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule

#-----------------------------------------------------zk 配置------------------------------------------------------
zookeeper:
  #每次重试时间间隔，单位毫秒
  baseSleepTimeMs: 1000
  #重试次数
  maxRetries: 3
  #zookeeper服务连接id与端口
  connectString: 192.168.50.50:2181
  #会话超时时间，单位毫秒
  sessionTimeoutMs: 5000
  #连接创建超时时间，单位毫秒
  connection-timeout-ms: 5000
#-----------------------------------------------------HYSTRIX-----------------------------------------------------
hystrix:
  threadpool:
    default:
      coreSize: 100
      maximumSize: 500
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 100
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3600000