
server:
  port: 20003

spring:
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
#          clone-on-start: true
          force-pull: true
#          timeout: 10
          # '{profile}'
          searchPaths: '{profile}'
        default-profile: ${spring.profiles.active}
      allow-override: true
      override-none: true
      override-system-properties: true
      label:
# 服务注册   服务发现配置
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:20000/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/info
management:
  endpoints:
    web:
      exposure:
        include: "*"