spring:
  cloud:
    config:
      server:
        git:
          username: hzqsultan@qq.com
          password: 2012hzqsultan
          uri: https://github.com/SultanDebug/config.git
          skipSslValidation: true